version: "3.9"

services:
  web:
    build: .
    command: python /code/src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./src/.env.dev
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django_dev 
      

volumes:
  postgres_data: