# Generated by Django 4.2.6 on 2023-11-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_researcher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
