# Generated by Django 4.2.6 on 2023-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_researcher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='role',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
