# Generated by Django 4.2.6 on 2024-02-08 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_animal_id_alter_experiment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaldata',
            name='size',
        ),
        migrations.RemoveField(
            model_name='animaldata',
            name='weight',
        ),
        migrations.AddField(
            model_name='animaldata',
            name='createdAt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animaldata',
            name='informations',
            field=models.JSONField(default=dict),
        ),
    ]
