# Generated by Django 4.2.6 on 2024-02-08 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_animaldata_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaldata',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 14, 55, 3, 178289, tzinfo=datetime.timezone.utc)),
        ),
    ]
