# Generated by Django 4.2.6 on 2024-02-08 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_animaldata_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDataFields',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('informations_fields', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_data_fields',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.animaldatafields'),
            preserve_default=False,
        ),
    ]
