# Generated by Django 4.2.6 on 2024-02-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_animaldatafields_animal_animal_data_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_data_fields',
        ),
        migrations.AddField(
            model_name='groupexperiment',
            name='animal_data_fields',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.animaldatafields'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animaldatafields',
            name='informations_fields',
            field=models.JSONField(default={'Campo1': 'exemplo'}),
        ),
    ]
