# Generated by Django 4.2.6 on 2024-02-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_animal_animal_data_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaldatafields',
            name='informations_fields',
            field=models.JSONField(default=dict),
        ),
    ]
