# Generated by Django 4.2.6 on 2024-03-05 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_animaldatafields_informations_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexperiment',
            name='animal_data_fields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.animaldatafields'),
        ),
    ]
